name = "bsws-bible-dynamic"
main = "worker.mjs"
compatibility_date = "2026-04-25"
account_id = "e34ee2bc488cabbbd453e589ba44075c"

routes = [
  { pattern = "bswsapp.com/bible/bengali/*", zone_name = "bswsapp.com" },
  { pattern = "bswsapp.com/bible/gujarati/*", zone_name = "bswsapp.com" },
  { pattern = "bswsapp.com/bible/hindi/*", zone_name = "bswsapp.com" },
  { pattern = "bswsapp.com/bible/kannada/*", zone_name = "bswsapp.com" },
  { pattern = "bswsapp.com/bible/malayalam/*", zone_name = "bswsapp.com" },
  { pattern = "bswsapp.com/bible/marathi/*", zone_name = "bswsapp.com" },
  { pattern = "bswsapp.com/bible/nepali/*", zone_name = "bswsapp.com" },
  { pattern = "bswsapp.com/bible/odia/*", zone_name = "bswsapp.com" },
  { pattern = "bswsapp.com/bible/tamil/*", zone_name = "bswsapp.com" },
  { pattern = "bswsapp.com/bible/parallel/*", zone_name = "bswsapp.com" },
  { pattern = "bswsapp.com/api/bible/*", zone_name = "bswsapp.com" },
  { pattern = "www.bswsapp.com/bible/bengali/*", zone_name = "bswsapp.com" },
  { pattern = "www.bswsapp.com/bible/gujarati/*", zone_name = "bswsapp.com" },
  { pattern = "www.bswsapp.com/bible/hindi/*", zone_name = "bswsapp.com" },
  { pattern = "www.bswsapp.com/bible/kannada/*", zone_name = "bswsapp.com" },
  { pattern = "www.bswsapp.com/bible/malayalam/*", zone_name = "bswsapp.com" },
  { pattern = "www.bswsapp.com/bible/marathi/*", zone_name = "bswsapp.com" },
  { pattern = "www.bswsapp.com/bible/nepali/*", zone_name = "bswsapp.com" },
  { pattern = "www.bswsapp.com/bible/odia/*", zone_name = "bswsapp.com" },
  { pattern = "www.bswsapp.com/bible/tamil/*", zone_name = "bswsapp.com" },
  { pattern = "www.bswsapp.com/bible/parallel/*", zone_name = "bswsapp.com" },
  { pattern = "www.bswsapp.com/api/bible/*", zone_name = "bswsapp.com" }
]
